// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/envsync-cloud/envsync-management-go-sdk/sdk/core"
	enterprise "github.com/envsync-cloud/envsync-management-go-sdk/sdk/enterprise"
	internal "github.com/envsync-cloud/envsync-management-go-sdk/sdk/internal"
	license "github.com/envsync-cloud/envsync-management-go-sdk/sdk/license"
	onboarding "github.com/envsync-cloud/envsync-management-go-sdk/sdk/onboarding"
	option "github.com/envsync-cloud/envsync-management-go-sdk/sdk/option"
	system "github.com/envsync-cloud/envsync-management-go-sdk/sdk/system"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Onboarding *onboarding.Client
	License    *license.Client
	Enterprise *enterprise.Client
	System     *system.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:     options.ToHeader(),
		Onboarding: onboarding.NewClient(opts...),
		License:    license.NewClient(opts...),
		Enterprise: enterprise.NewClient(opts...),
		System:     system.NewClient(opts...),
	}
}
