// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	core "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/core"
)

// Invalid export request
type BadRequestError struct {
	*core.APIError
	Body *ErrorResponse
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// Internal server error
type InternalServerError struct {
	*core.APIError
	Body interface{}
}

func (i *InternalServerError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 500
	i.Body = body
	return nil
}

func (i *InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InternalServerError) Unwrap() error {
	return i.APIError
}

// Organization CA not initialized
type NotFoundError struct {
	*core.APIError
	Body *ErrorResponse
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// Validation error
type UnprocessableEntityError struct {
	*core.APIError
	Body *ErrorResponse
}

func (u *UnprocessableEntityError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 422
	u.Body = body
	return nil
}

func (u *UnprocessableEntityError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnprocessableEntityError) Unwrap() error {
	return u.APIError
}
