// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type EffectiveAccessResponse = []*EffectiveAccessResponseItem

type EffectiveAccessResponseItem struct {
	UserId   string   `json:"user_id" url:"user_id"`
	Email    string   `json:"email" url:"email"`
	Relation *string  `json:"relation,omitempty" url:"relation,omitempty"`
	Source   *string  `json:"source,omitempty" url:"source,omitempty"`
	Teams    []string `json:"teams" url:"teams"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EffectiveAccessResponseItem) GetUserId() string {
	if e == nil {
		return ""
	}
	return e.UserId
}

func (e *EffectiveAccessResponseItem) GetEmail() string {
	if e == nil {
		return ""
	}
	return e.Email
}

func (e *EffectiveAccessResponseItem) GetRelation() *string {
	if e == nil {
		return nil
	}
	return e.Relation
}

func (e *EffectiveAccessResponseItem) GetSource() *string {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *EffectiveAccessResponseItem) GetTeams() []string {
	if e == nil {
		return nil
	}
	return e.Teams
}

func (e *EffectiveAccessResponseItem) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EffectiveAccessResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler EffectiveAccessResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EffectiveAccessResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EffectiveAccessResponseItem) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type GrantAccessRequest struct {
	SubjectId   string                        `json:"subject_id" url:"subject_id"`
	SubjectType GrantAccessRequestSubjectType `json:"subject_type" url:"subject_type"`
	Relation    GrantAccessRequestRelation    `json:"relation" url:"relation"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GrantAccessRequest) GetSubjectId() string {
	if g == nil {
		return ""
	}
	return g.SubjectId
}

func (g *GrantAccessRequest) GetSubjectType() GrantAccessRequestSubjectType {
	if g == nil {
		return ""
	}
	return g.SubjectType
}

func (g *GrantAccessRequest) GetRelation() GrantAccessRequestRelation {
	if g == nil {
		return ""
	}
	return g.Relation
}

func (g *GrantAccessRequest) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GrantAccessRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GrantAccessRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GrantAccessRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GrantAccessRequest) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GrantAccessRequestRelation string

const (
	GrantAccessRequestRelationAdmin  GrantAccessRequestRelation = "admin"
	GrantAccessRequestRelationEditor GrantAccessRequestRelation = "editor"
	GrantAccessRequestRelationViewer GrantAccessRequestRelation = "viewer"
)

func NewGrantAccessRequestRelationFromString(s string) (GrantAccessRequestRelation, error) {
	switch s {
	case "admin":
		return GrantAccessRequestRelationAdmin, nil
	case "editor":
		return GrantAccessRequestRelationEditor, nil
	case "viewer":
		return GrantAccessRequestRelationViewer, nil
	}
	var t GrantAccessRequestRelation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantAccessRequestRelation) Ptr() *GrantAccessRequestRelation {
	return &g
}

type GrantAccessRequestSubjectType string

const (
	GrantAccessRequestSubjectTypeUser GrantAccessRequestSubjectType = "user"
	GrantAccessRequestSubjectTypeTeam GrantAccessRequestSubjectType = "team"
)

func NewGrantAccessRequestSubjectTypeFromString(s string) (GrantAccessRequestSubjectType, error) {
	switch s {
	case "user":
		return GrantAccessRequestSubjectTypeUser, nil
	case "team":
		return GrantAccessRequestSubjectTypeTeam, nil
	}
	var t GrantAccessRequestSubjectType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantAccessRequestSubjectType) Ptr() *GrantAccessRequestSubjectType {
	return &g
}

type GrantsListResponse = []*GrantsListResponseItem

type GrantsListResponseItem struct {
	SubjectId   string                            `json:"subject_id" url:"subject_id"`
	SubjectType GrantsListResponseItemSubjectType `json:"subject_type" url:"subject_type"`
	Relation    GrantsListResponseItemRelation    `json:"relation" url:"relation"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GrantsListResponseItem) GetSubjectId() string {
	if g == nil {
		return ""
	}
	return g.SubjectId
}

func (g *GrantsListResponseItem) GetSubjectType() GrantsListResponseItemSubjectType {
	if g == nil {
		return ""
	}
	return g.SubjectType
}

func (g *GrantsListResponseItem) GetRelation() GrantsListResponseItemRelation {
	if g == nil {
		return ""
	}
	return g.Relation
}

func (g *GrantsListResponseItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GrantsListResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GrantsListResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GrantsListResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GrantsListResponseItem) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GrantsListResponseItemRelation string

const (
	GrantsListResponseItemRelationAdmin  GrantsListResponseItemRelation = "admin"
	GrantsListResponseItemRelationEditor GrantsListResponseItemRelation = "editor"
	GrantsListResponseItemRelationViewer GrantsListResponseItemRelation = "viewer"
)

func NewGrantsListResponseItemRelationFromString(s string) (GrantsListResponseItemRelation, error) {
	switch s {
	case "admin":
		return GrantsListResponseItemRelationAdmin, nil
	case "editor":
		return GrantsListResponseItemRelationEditor, nil
	case "viewer":
		return GrantsListResponseItemRelationViewer, nil
	}
	var t GrantsListResponseItemRelation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantsListResponseItemRelation) Ptr() *GrantsListResponseItemRelation {
	return &g
}

type GrantsListResponseItemSubjectType string

const (
	GrantsListResponseItemSubjectTypeUser GrantsListResponseItemSubjectType = "user"
	GrantsListResponseItemSubjectTypeTeam GrantsListResponseItemSubjectType = "team"
)

func NewGrantsListResponseItemSubjectTypeFromString(s string) (GrantsListResponseItemSubjectType, error) {
	switch s {
	case "user":
		return GrantsListResponseItemSubjectTypeUser, nil
	case "team":
		return GrantsListResponseItemSubjectTypeTeam, nil
	}
	var t GrantsListResponseItemSubjectType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantsListResponseItemSubjectType) Ptr() *GrantsListResponseItemSubjectType {
	return &g
}

type PermissionMessageResponse struct {
	Message string `json:"message" url:"message"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PermissionMessageResponse) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *PermissionMessageResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PermissionMessageResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PermissionMessageResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PermissionMessageResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PermissionMessageResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type RevokeAccessRequest struct {
	SubjectId   string                         `json:"subject_id" url:"subject_id"`
	SubjectType RevokeAccessRequestSubjectType `json:"subject_type" url:"subject_type"`
	Relation    RevokeAccessRequestRelation    `json:"relation" url:"relation"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokeAccessRequest) GetSubjectId() string {
	if r == nil {
		return ""
	}
	return r.SubjectId
}

func (r *RevokeAccessRequest) GetSubjectType() RevokeAccessRequestSubjectType {
	if r == nil {
		return ""
	}
	return r.SubjectType
}

func (r *RevokeAccessRequest) GetRelation() RevokeAccessRequestRelation {
	if r == nil {
		return ""
	}
	return r.Relation
}

func (r *RevokeAccessRequest) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RevokeAccessRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RevokeAccessRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RevokeAccessRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokeAccessRequest) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RevokeAccessRequestRelation string

const (
	RevokeAccessRequestRelationAdmin  RevokeAccessRequestRelation = "admin"
	RevokeAccessRequestRelationEditor RevokeAccessRequestRelation = "editor"
	RevokeAccessRequestRelationViewer RevokeAccessRequestRelation = "viewer"
)

func NewRevokeAccessRequestRelationFromString(s string) (RevokeAccessRequestRelation, error) {
	switch s {
	case "admin":
		return RevokeAccessRequestRelationAdmin, nil
	case "editor":
		return RevokeAccessRequestRelationEditor, nil
	case "viewer":
		return RevokeAccessRequestRelationViewer, nil
	}
	var t RevokeAccessRequestRelation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RevokeAccessRequestRelation) Ptr() *RevokeAccessRequestRelation {
	return &r
}

type RevokeAccessRequestSubjectType string

const (
	RevokeAccessRequestSubjectTypeUser RevokeAccessRequestSubjectType = "user"
	RevokeAccessRequestSubjectTypeTeam RevokeAccessRequestSubjectType = "team"
)

func NewRevokeAccessRequestSubjectTypeFromString(s string) (RevokeAccessRequestSubjectType, error) {
	switch s {
	case "user":
		return RevokeAccessRequestSubjectTypeUser, nil
	case "team":
		return RevokeAccessRequestSubjectTypeTeam, nil
	}
	var t RevokeAccessRequestSubjectType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RevokeAccessRequestSubjectType) Ptr() *RevokeAccessRequestSubjectType {
	return &r
}
