// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type EffectiveAccessEntry struct {
	UserId         string                            `json:"user_id" url:"user_id"`
	Email          string                            `json:"email" url:"email"`
	Relation       *string                           `json:"relation,omitempty" url:"relation,omitempty"`
	OrgRelation    *string                           `json:"org_relation,omitempty" url:"org_relation,omitempty"`
	DirectRelation *string                           `json:"direct_relation,omitempty" url:"direct_relation,omitempty"`
	TeamRelation   *string                           `json:"team_relation,omitempty" url:"team_relation,omitempty"`
	Sources        []EffectiveAccessEntrySourcesItem `json:"sources" url:"sources"`
	Teams          []string                          `json:"teams" url:"teams"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EffectiveAccessEntry) GetUserId() string {
	if e == nil {
		return ""
	}
	return e.UserId
}

func (e *EffectiveAccessEntry) GetEmail() string {
	if e == nil {
		return ""
	}
	return e.Email
}

func (e *EffectiveAccessEntry) GetRelation() *string {
	if e == nil {
		return nil
	}
	return e.Relation
}

func (e *EffectiveAccessEntry) GetOrgRelation() *string {
	if e == nil {
		return nil
	}
	return e.OrgRelation
}

func (e *EffectiveAccessEntry) GetDirectRelation() *string {
	if e == nil {
		return nil
	}
	return e.DirectRelation
}

func (e *EffectiveAccessEntry) GetTeamRelation() *string {
	if e == nil {
		return nil
	}
	return e.TeamRelation
}

func (e *EffectiveAccessEntry) GetSources() []EffectiveAccessEntrySourcesItem {
	if e == nil {
		return nil
	}
	return e.Sources
}

func (e *EffectiveAccessEntry) GetTeams() []string {
	if e == nil {
		return nil
	}
	return e.Teams
}

func (e *EffectiveAccessEntry) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EffectiveAccessEntry) UnmarshalJSON(data []byte) error {
	type unmarshaler EffectiveAccessEntry
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EffectiveAccessEntry(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EffectiveAccessEntry) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type EffectiveAccessEntrySourcesItem string

const (
	EffectiveAccessEntrySourcesItemOrg    EffectiveAccessEntrySourcesItem = "org"
	EffectiveAccessEntrySourcesItemDirect EffectiveAccessEntrySourcesItem = "direct"
	EffectiveAccessEntrySourcesItemTeam   EffectiveAccessEntrySourcesItem = "team"
)

func NewEffectiveAccessEntrySourcesItemFromString(s string) (EffectiveAccessEntrySourcesItem, error) {
	switch s {
	case "org":
		return EffectiveAccessEntrySourcesItemOrg, nil
	case "direct":
		return EffectiveAccessEntrySourcesItemDirect, nil
	case "team":
		return EffectiveAccessEntrySourcesItemTeam, nil
	}
	var t EffectiveAccessEntrySourcesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e EffectiveAccessEntrySourcesItem) Ptr() *EffectiveAccessEntrySourcesItem {
	return &e
}

type EffectiveAccessResponse = []*EffectiveAccessEntry

type GrantAccessRequest struct {
	SubjectId   string                        `json:"subject_id" url:"subject_id"`
	SubjectType GrantAccessRequestSubjectType `json:"subject_type" url:"subject_type"`
	Relation    GrantAccessRequestRelation    `json:"relation" url:"relation"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GrantAccessRequest) GetSubjectId() string {
	if g == nil {
		return ""
	}
	return g.SubjectId
}

func (g *GrantAccessRequest) GetSubjectType() GrantAccessRequestSubjectType {
	if g == nil {
		return ""
	}
	return g.SubjectType
}

func (g *GrantAccessRequest) GetRelation() GrantAccessRequestRelation {
	if g == nil {
		return ""
	}
	return g.Relation
}

func (g *GrantAccessRequest) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GrantAccessRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GrantAccessRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GrantAccessRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GrantAccessRequest) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GrantAccessRequestRelation string

const (
	GrantAccessRequestRelationAdmin  GrantAccessRequestRelation = "admin"
	GrantAccessRequestRelationEditor GrantAccessRequestRelation = "editor"
	GrantAccessRequestRelationViewer GrantAccessRequestRelation = "viewer"
)

func NewGrantAccessRequestRelationFromString(s string) (GrantAccessRequestRelation, error) {
	switch s {
	case "admin":
		return GrantAccessRequestRelationAdmin, nil
	case "editor":
		return GrantAccessRequestRelationEditor, nil
	case "viewer":
		return GrantAccessRequestRelationViewer, nil
	}
	var t GrantAccessRequestRelation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantAccessRequestRelation) Ptr() *GrantAccessRequestRelation {
	return &g
}

type GrantAccessRequestSubjectType string

const (
	GrantAccessRequestSubjectTypeUser GrantAccessRequestSubjectType = "user"
	GrantAccessRequestSubjectTypeTeam GrantAccessRequestSubjectType = "team"
)

func NewGrantAccessRequestSubjectTypeFromString(s string) (GrantAccessRequestSubjectType, error) {
	switch s {
	case "user":
		return GrantAccessRequestSubjectTypeUser, nil
	case "team":
		return GrantAccessRequestSubjectTypeTeam, nil
	}
	var t GrantAccessRequestSubjectType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantAccessRequestSubjectType) Ptr() *GrantAccessRequestSubjectType {
	return &g
}

type GrantEntry struct {
	SubjectId   string                `json:"subject_id" url:"subject_id"`
	SubjectType GrantEntrySubjectType `json:"subject_type" url:"subject_type"`
	Relation    GrantEntryRelation    `json:"relation" url:"relation"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GrantEntry) GetSubjectId() string {
	if g == nil {
		return ""
	}
	return g.SubjectId
}

func (g *GrantEntry) GetSubjectType() GrantEntrySubjectType {
	if g == nil {
		return ""
	}
	return g.SubjectType
}

func (g *GrantEntry) GetRelation() GrantEntryRelation {
	if g == nil {
		return ""
	}
	return g.Relation
}

func (g *GrantEntry) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GrantEntry) UnmarshalJSON(data []byte) error {
	type unmarshaler GrantEntry
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GrantEntry(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GrantEntry) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GrantEntryRelation string

const (
	GrantEntryRelationAdmin  GrantEntryRelation = "admin"
	GrantEntryRelationEditor GrantEntryRelation = "editor"
	GrantEntryRelationViewer GrantEntryRelation = "viewer"
)

func NewGrantEntryRelationFromString(s string) (GrantEntryRelation, error) {
	switch s {
	case "admin":
		return GrantEntryRelationAdmin, nil
	case "editor":
		return GrantEntryRelationEditor, nil
	case "viewer":
		return GrantEntryRelationViewer, nil
	}
	var t GrantEntryRelation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantEntryRelation) Ptr() *GrantEntryRelation {
	return &g
}

type GrantEntrySubjectType string

const (
	GrantEntrySubjectTypeUser GrantEntrySubjectType = "user"
	GrantEntrySubjectTypeTeam GrantEntrySubjectType = "team"
)

func NewGrantEntrySubjectTypeFromString(s string) (GrantEntrySubjectType, error) {
	switch s {
	case "user":
		return GrantEntrySubjectTypeUser, nil
	case "team":
		return GrantEntrySubjectTypeTeam, nil
	}
	var t GrantEntrySubjectType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantEntrySubjectType) Ptr() *GrantEntrySubjectType {
	return &g
}

type GrantsListResponse = []*GrantEntry

type PermissionMessageResponse struct {
	Message string `json:"message" url:"message"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PermissionMessageResponse) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *PermissionMessageResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PermissionMessageResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PermissionMessageResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PermissionMessageResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PermissionMessageResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type RevokeAccessRequest struct {
	SubjectId   string                         `json:"subject_id" url:"subject_id"`
	SubjectType RevokeAccessRequestSubjectType `json:"subject_type" url:"subject_type"`
	Relation    RevokeAccessRequestRelation    `json:"relation" url:"relation"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokeAccessRequest) GetSubjectId() string {
	if r == nil {
		return ""
	}
	return r.SubjectId
}

func (r *RevokeAccessRequest) GetSubjectType() RevokeAccessRequestSubjectType {
	if r == nil {
		return ""
	}
	return r.SubjectType
}

func (r *RevokeAccessRequest) GetRelation() RevokeAccessRequestRelation {
	if r == nil {
		return ""
	}
	return r.Relation
}

func (r *RevokeAccessRequest) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RevokeAccessRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RevokeAccessRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RevokeAccessRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokeAccessRequest) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RevokeAccessRequestRelation string

const (
	RevokeAccessRequestRelationAdmin  RevokeAccessRequestRelation = "admin"
	RevokeAccessRequestRelationEditor RevokeAccessRequestRelation = "editor"
	RevokeAccessRequestRelationViewer RevokeAccessRequestRelation = "viewer"
)

func NewRevokeAccessRequestRelationFromString(s string) (RevokeAccessRequestRelation, error) {
	switch s {
	case "admin":
		return RevokeAccessRequestRelationAdmin, nil
	case "editor":
		return RevokeAccessRequestRelationEditor, nil
	case "viewer":
		return RevokeAccessRequestRelationViewer, nil
	}
	var t RevokeAccessRequestRelation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RevokeAccessRequestRelation) Ptr() *RevokeAccessRequestRelation {
	return &r
}

type RevokeAccessRequestSubjectType string

const (
	RevokeAccessRequestSubjectTypeUser RevokeAccessRequestSubjectType = "user"
	RevokeAccessRequestSubjectTypeTeam RevokeAccessRequestSubjectType = "team"
)

func NewRevokeAccessRequestSubjectTypeFromString(s string) (RevokeAccessRequestSubjectType, error) {
	switch s {
	case "user":
		return RevokeAccessRequestSubjectTypeUser, nil
	case "team":
		return RevokeAccessRequestSubjectTypeTeam, nil
	}
	var t RevokeAccessRequestSubjectType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RevokeAccessRequestSubjectType) Ptr() *RevokeAccessRequestSubjectType {
	return &r
}
