receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    root_path: /hostfs
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      load:
      network:
      paging:
      processes:
  filelog/docker:
    include:
      - /var/lib/docker/containers/*/*-json.log
    start_at: beginning
    include_file_path: true

processors:
  batch: {}
  resource:
    attributes:
      - key: deployment.environment
        action: upsert
        value: local
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: [os]

exporters:
  otlphttp/clickstack:
    endpoint: http://clickstack:4318
__CLICKSTACK_OTLP_HEADERS__
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, resource, batch]
      exporters: [otlphttp/clickstack, debug]
    logs:
      receivers: [otlp, filelog/docker]
      processors: [resourcedetection, resource, batch]
      exporters: [otlphttp/clickstack]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resourcedetection, resource, batch]
      exporters: [otlphttp/clickstack]
