events {}

stream {
  server {
    listen 5432;
    proxy_pass postgres:5432;
  }
  server {
    listen 6379;
    proxy_pass redis:6379;
  }
  server {
    listen 50051;
    proxy_pass minikms:50051;
  }
  server {
    listen 5544;
    proxy_pass minikms_db:5432;
  }
  server {
    listen 8091;
    proxy_pass openfga:8091;
  }
}

http {
  server {
    listen 80;
    server_name keycloak.envsync.local;
    location / {
      proxy_pass http://keycloak:8080/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
  server {
    listen 80;
    server_name openfga.envsync.local;
    location / {
      proxy_pass http://openfga:8090/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
  server {
    listen 80;
    server_name clickstack.envsync.local;
    location / {
      proxy_pass http://clickstack:8080/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
  server {
    listen 80;
    server_name rustfs.envsync.local;
    location / {
      proxy_pass http://rustfs:9001/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
  server {
    listen 80;
    server_name mailpit.envsync.local;
    location / {
      proxy_pass http://mailpit:8025/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}