import { mkdirSync, writeFileSync, unlinkSync } from "node:fs";
import { resolve, join } from "node:path";
import pino, { type Bindings } from "pino";
import { trace, isSpanContextValid, context } from "@opentelemetry/api";
import { logs, SeverityNumber } from "@opentelemetry/api-logs";

export enum LogTypes {
	LOGS = "logs",
	ERROR = "error",
	CUSTOMOBJ = "customObj",
}

const LOGS_DIR = join(resolve(import.meta.dir, "../../../../.."), "logs");

function createFileDestination(fileName: string) {
	try {
		mkdirSync(LOGS_DIR, { recursive: true });
		const probePath = join(LOGS_DIR, ".write-test");
		writeFileSync(probePath, "");
		unlinkSync(probePath);
		return pino.destination({ dest: join(LOGS_DIR, fileName), sync: false, mkdir: true });
	} catch {
		return null;
	}
}

const appLogDestination = createFileDestination("app.log");
const apiResponseLogDestination = createFileDestination("api-responses.log");

// Singleton Pino instance with trace context mixin for OTEL log-trace correlation
const logger = pino({
	mixin() {
		const span = trace.getActiveSpan();
		if (span) {
			const ctx = span.spanContext();
			if (isSpanContextValid(ctx)) {
				return {
					trace_id: ctx.traceId,
					span_id: ctx.spanId,
					trace_flags: `0${ctx.traceFlags.toString(16)}`,
				};
			}
		}
		return {};
	},
}, pino.multistream([
	{ stream: process.stdout },
	...(appLogDestination ? [{ stream: appLogDestination }] : []),
]));

// API response logger: file only
export const apiResponseLogger = pino(
	{},
	apiResponseLogDestination ?? process.stdout,
);

function emitOtelLog(body: string, severityNumber: SeverityNumber, severityText: string, generatedBy: string) {
	const otelLogger = logs.getLogger("envsync-api");
	const span = trace.getSpan(context.active());
	const isError = severityText === "ERROR";

	otelLogger.emit({
		severityNumber,
		severityText,
		body,
		attributes: {
			"log.source": "pino",
			"log.generated_by": generatedBy,
			...(isError
				? {
						"envsync.event_name": "api_error",
						"envsync.event_category": "api_error",
					}
				: {}),
			...(span
				? {
						"trace.id": span.spanContext().traceId,
						"span.id": span.spanContext().spanId,
					}
				: {}),
		},
	});
}

/**
 * Function to log the messages
 * @param msg  Message to be logged
 * @param logType Type of log
 * @param generated_by Generated by
 * @returns Log
 */
const infoLogs = (msg: string | Bindings, logType: LogTypes, generated_by: string) => {
	if (
		generated_by &&
		[LogTypes.LOGS, LogTypes.ERROR].includes(logType) &&
		typeof msg === "string"
	) {
		msg = `[${generated_by}] ` + msg;
	}
	if (logType === LogTypes.LOGS && typeof msg === "string") {
		emitOtelLog(msg, SeverityNumber.INFO, "INFO", generated_by);
		return logger.info(msg);
	}
	if (logType === LogTypes.ERROR && typeof msg === "string") {
		emitOtelLog(msg, SeverityNumber.ERROR, "ERROR", generated_by);
		return logger.error(msg);
	}
	if (logType === LogTypes.CUSTOMOBJ) {
		if (typeof msg === "string") {
			return logger.info({ generated_by }, msg);
		}
		return logger.info(generated_by ? { generated_by, ...msg } : msg);
	}
	return logger.info(generated_by ? { generated_by, payload: msg } : { payload: msg });
};

export default infoLogs;
