// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/envsync-cloud/envsync-management-go-sdk/sdk/internal"
)

type SystemStatusResponse struct {
	System  *SystemStatusState     `json:"system" url:"system"`
	License *LicenseStatusResponse `json:"license" url:"license"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SystemStatusResponse) GetSystem() *SystemStatusState {
	if s == nil {
		return nil
	}
	return s.System
}

func (s *SystemStatusResponse) GetLicense() *LicenseStatusResponse {
	if s == nil {
		return nil
	}
	return s.License
}

func (s *SystemStatusResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SystemStatusResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SystemStatusResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SystemStatusResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SystemStatusResponse) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SystemStatusState struct {
	Edition                   SystemStatusStateEdition `json:"edition" url:"edition"`
	SingleOrgMode             bool                     `json:"single_org_mode" url:"single_org_mode"`
	ManagementEnabled         bool                     `json:"management_enabled" url:"management_enabled"`
	ObservabilityEnabled      bool                     `json:"observability_enabled" url:"observability_enabled"`
	ManagementWebEnabled      bool                     `json:"management_web_enabled" url:"management_web_enabled"`
	LandingEnabled            bool                     `json:"landing_enabled" url:"landing_enabled"`
	FirstBootstrapCompletedAt *string                  `json:"first_bootstrap_completed_at,omitempty" url:"first_bootstrap_completed_at,omitempty"`
	OrgCount                  float64                  `json:"org_count" url:"org_count"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SystemStatusState) GetEdition() SystemStatusStateEdition {
	if s == nil {
		return ""
	}
	return s.Edition
}

func (s *SystemStatusState) GetSingleOrgMode() bool {
	if s == nil {
		return false
	}
	return s.SingleOrgMode
}

func (s *SystemStatusState) GetManagementEnabled() bool {
	if s == nil {
		return false
	}
	return s.ManagementEnabled
}

func (s *SystemStatusState) GetObservabilityEnabled() bool {
	if s == nil {
		return false
	}
	return s.ObservabilityEnabled
}

func (s *SystemStatusState) GetManagementWebEnabled() bool {
	if s == nil {
		return false
	}
	return s.ManagementWebEnabled
}

func (s *SystemStatusState) GetLandingEnabled() bool {
	if s == nil {
		return false
	}
	return s.LandingEnabled
}

func (s *SystemStatusState) GetFirstBootstrapCompletedAt() *string {
	if s == nil {
		return nil
	}
	return s.FirstBootstrapCompletedAt
}

func (s *SystemStatusState) GetOrgCount() float64 {
	if s == nil {
		return 0
	}
	return s.OrgCount
}

func (s *SystemStatusState) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SystemStatusState) UnmarshalJSON(data []byte) error {
	type unmarshaler SystemStatusState
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SystemStatusState(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SystemStatusState) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SystemStatusStateEdition string

const (
	SystemStatusStateEditionOss        SystemStatusStateEdition = "oss"
	SystemStatusStateEditionEnterprise SystemStatusStateEdition = "enterprise"
)

func NewSystemStatusStateEditionFromString(s string) (SystemStatusStateEdition, error) {
	switch s {
	case "oss":
		return SystemStatusStateEditionOss, nil
	case "enterprise":
		return SystemStatusStateEditionEnterprise, nil
	}
	var t SystemStatusStateEdition
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SystemStatusStateEdition) Ptr() *SystemStatusStateEdition {
	return &s
}
