import { readFileSync, writeFileSync } from "node:fs";

const TEMPLATE_PATH = "docker/otel-agent/otel-agent-config.local.tmpl.yaml";
const OUTPUT_PATH = "docker/otel-agent/otel-agent-config.local.yaml";
const ROOT_ENV_LOCAL_PATH = ".env.local";
const CLICKSTACK_CONTAINER = "monorepo-clickstack-1";
const CLICKSTACK_HEALTH_URL = "http://localhost:8800";

function run(cmd: string[]) {
	const proc = Bun.spawnSync(cmd, {
		stdout: "pipe",
		stderr: "pipe",
	});

	if (proc.exitCode !== 0) {
		throw new Error(Buffer.from(proc.stderr).toString() || `Command failed: ${cmd.join(" ")}`);
	}

	return Buffer.from(proc.stdout).toString().trim();
}

function sleep(ms: number) {
	return new Promise(resolve => setTimeout(resolve, ms));
}

async function waitForClickstack() {
	for (let attempt = 1; attempt <= 30; attempt++) {
		try {
			const inspect = Bun.spawnSync([
				"docker",
				"inspect",
				"--format",
				"{{.State.Health.Status}}",
				CLICKSTACK_CONTAINER,
			], {
				stdout: "pipe",
				stderr: "pipe",
			});

			const health = Buffer.from(inspect.stdout).toString().trim();
			if (inspect.exitCode === 0 && health === "healthy") {
				const res = await fetch(CLICKSTACK_HEALTH_URL, { redirect: "manual" });
				if (res.ok || res.status === 302 || res.status === 401) {
					return;
				}
			}
		} catch {
			// wait and retry
		}

		await sleep(1000);
	}

	throw new Error("ClickStack did not become ready in time");
}

function getClickstackToken() {
	const script = "sed -n '/bearertokenauth\\/hyperdx:/,/^[^ ]/p' /etc/otel/supervisor-data/effective.yaml | sed -n 's/^ *- //p' | head -n1";

	return run([
		"docker",
		"exec",
		CLICKSTACK_CONTAINER,
		"sh",
		"-lc",
		script,
	]);
}

function getClickstackEnv(name: string) {
	return run([
		"docker",
		"inspect",
		"--format",
		`{{range .Config.Env}}{{println .}}{{end}}`,
		CLICKSTACK_CONTAINER,
	])
		.split("\n")
		.map((line) => line.trim())
		.find((line) => line.startsWith(`${name}=`))
		?.slice(name.length + 1) ?? "";
}

function resolveClickstackConfig() {
	const token = getClickstackToken();
	if (token) {
		return {
			apiKey: token,
			otelHeaders: ['    headers:', `      Authorization: ${token}`].join("\n"),
			mode: "token",
		};
	}

	const localApiKey = getClickstackEnv("INGESTION_API_KEY");
	return {
		apiKey: localApiKey,
		otelHeaders: "",
		mode: localApiKey ? "noauth-env" : "noauth-empty",
	};
}

async function main() {
	const config = resolveClickstackConfig();

	const template = readFileSync(TEMPLATE_PATH, "utf8");
	const rendered = template.replace("__CLICKSTACK_OTLP_HEADERS__", config.otelHeaders);
	writeFileSync(OUTPUT_PATH, rendered);
	writeFileSync(
		ROOT_ENV_LOCAL_PATH,
		[
			"# Generated by bun run clickstack:sync",
			`VITE_HYPERDX_API_KEY=${config.apiKey}`,
			"VITE_HYPERDX_URL=http://localhost:4318",
			"VITE_HYPERDX_DISABLED=false",
			"VITE_OTEL_ENDPOINT=http://localhost:4318",
			"OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:14318",
			"",
		].join("\n"),
	);

	run(["docker", "compose", "up", "-d", "--force-recreate", "otel-agent"]);
	await waitForClickstack();
	run(["bun", "run", "scripts/bootstrap-clickstack-local.ts"]);

	console.log(`Synced local ClickStack config for ${config.mode} mode`);
}

await main();
