{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "envsync.fullname" . }}-web
  labels:
    {{- include "envsync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "envsync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
{{- end }}
